language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
env:
  global:
    - describe
 test:
   adapter: mysql12
   database: testdb
   username: travis
   encoding: utf8